# Generated by Django 5.1.6 on 2025-02-19 03:24

import users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.manager.CustomUserManager()),
            ],
        ),
    ]
