# Generated by Django 5.1.6 on 2025-02-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_specialty_patient_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-id'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['-id'], 'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctors',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
        migrations.AlterModelTable(
            name='specialty',
            table='specialties',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
