# Generated by Django 5.1.6 on 2025-02-19 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_specialty_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('F', 'Finished'), ('C', 'Canceled')], max_length=1)),
                ('observations', models.CharField(default='', max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consultations', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consultations', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='consultations.consultation')),
            ],
        ),
    ]
