# Generated by Django 5.1.6 on 2025-02-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-id'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-id'], 'verbose_name': 'Consultation', 'verbose_name_plural': 'Consultations'},
        ),
        migrations.AlterField(
            model_name='consultation',
            name='observations',
            field=models.CharField(default='Sem observações', max_length=200),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('F', 'Finished'), ('C', 'Canceled')], default='S', max_length=1),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='attendances',
        ),
        migrations.AlterModelTable(
            name='consultation',
            table='consultations',
        ),
    ]
